### ISSUE TITLE
Error, when using modifiers

### ISSUE THREAD

**Issue by Tofel** [AurorNZ/paths-filter#12]
Hey!

Great job with changing `picomatch` for `minimatch`, now I can finally exclude paths as expected :-)

Unfortunately I've run into issue, when using modifiers (`added`, `modified`, `deleted`). 
I'm getting following error: `Invalid filter YAML format: Unexpected element type 'object'.`

When trying to use following filters:
```
filters: |
  sol:
    - added|modified: 'contracts/src/v0.8/**/*.sol'
```

Same syntax works with `dorny/paths-filters@de90cc6fb38fc0963ad72b210f1f284cd68cea36`, but with your's `3b1f3abc3371cca888d8eb03dfa70bc8a9867629` fails.

Any chances you could have a look? I had a quick look at diff commits, but didn't see any indicating any changes to that functionality.

Cheers!

**Comment by Obi-Dann** [comment]
Hi @Tofel, sorry for a late reply.

We took added|modified functionality out to simplify filters and forgot to mention it in the docs.

The latest [3.0.2](https://github.com/dorny/paths-filter/releases/tag/v3.0.2) release of https://github.com/dorny/paths-filter adds a new property `predicate-quantifier: 'every"` that should achieve the same behavior as `micromatch`.

We're considering to archive this repo in favor of https://github.com/dorny/paths-filter because it's more feature complete and better maintained

**Comment by Obi-Dann** [comment]
I sugesst an alternative approach because micromatch's logic cannot sanely combine with `added|modified`
The alternative approch is to extend the output with more fields like `_anyModified`, `_anyAdded` and `_anyDeleted` (the field names are WIP ;) )
so in your example, you'd use the following filters schema
```
- uses: AurorNZ/paths-filter@v4
   id: filter
  with:
    filters: |
      sol:
        - 'contracts/src/v0.8/**/*.sol'
```
and then check for modified or added files
```
- name: Do something
  if: ${{ steps.filter.outputs.sol_anyModified == 'true' ||  steps.filter.outputs.sol_anyAdded == 'true' }}
  run: ...
```

This is a rough idea, but it should allow us to continue using simple micromatch patterns and get the behaviour you need

**Comment by Tofel** [comment]
Eventually, I was able to achieve what I wanted with `dorny/paths-filter`, thank you for responding, though :-)
